---

- name: Create user
  user:
    name: "{{ username }}"
    state: present
    shell: "/bin/bash"
    createhome: yes

- name: Copy public key to authorized_keys
  authorized_key:
    user: "{{ username }}"
    key: "{{ public_key }}"

- name: Add user to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
    insertafter: '^#.*includedir.*sudoers.d'
