---
- name: Jenkins Lab
  hosts: all
  become: true

  vars:
    jenkins_port: 8080
    package_list: 
      - openjdk-11-jre 
      - jenkins
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  
  roles:
    - role: user
    - role: add_packages
    - role: jenkins_management